# Generated by Django 5.1.1 on 2024-09-20 00:04

import django.core.validators
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[products.validators.TitleValidator], verbose_name='Название')),
                ('description', models.TextField(max_length=512, validators=[products.validators.TextValidator], verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(999999.99)], verbose_name='Цена')),
            ],
        ),
    ]
